### ISSUE TITLE
블로깅 스터디 TWIL 참여 요청

### ISSUE THREAD

**Issue by kooku94** [week-with-me/TWIL#3]
## 문의사항을 골라주세요. :white:check_mark:
- [x] 스터디 참여 요청
- [ ] 기타 문의사항

### 아래 양식에 맞춰 작성하여 신청해주세요. :white_check_mark:
> 본인의 문의사항에 맞춰 알맞은 내용을 작성하여 주세요. 맨 아래 공통 작성사항이 있습니다.
---
##### - 희망하는 스터디

- [x] 블로깅 스터디 TWIL
---
##### 아래 자유롭게 문의하실 내용을 적어주세요.
스터디에 참여하고 싶습니다.
---
#### 공통 작성사항
> 이미 스터디를 진행 중인 사람인 경우 아래를 따로 작성하지 않으셔도 됩니다.

##### 1. 본인 실명 (필수)
구민규

##### 2. Slack 계정 아이디 (필수)
koomg9599@gmail.com

##### 3. GitHub 계정 아이디 (필수)
kooku94

**Comment by 0417taehyun** [comment]
안녕하세요. 우선 신청해주셔서 감사합니다 8월 8일 1회차가 끝난 이후에 2회차 때 슬랙 초대해드리겠습니다. 관심 가져주셔서 다시 한 번 감사합니다. 이슈는 초대 이후에 닫도록 하겠습니다.
